### PR TITLE
fix: hype train last contribution should be single object

### LINKED ISSUE #2: Exception with HypeTrainBegin event
It seems the Twitchlib.EventSub module doesn't work with the channel.hype_train.begin event

It crashes on the LastContribution object which expects an array of HypeTrainContribution
But it's only a single element

image

[Error] WebApp.Services.EventSubService: Reason: Application_Error - Message: The JSON value could not be converted to TwitchLib.EventSub.Webhooks.Core.Models.HypeTrain.HypeTrainContribution[]. Path: $.event.last_contribution | LineNumber: 0 | BytePositionInLine: 738.

### PR DESCRIPTION
**Pull request by iProdigy**
Fixes #2 

https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelhype_trainbegin

### CODE REVIEW

**Review by Syzuna — APPROVED** [review]
LGTM!
Thanks

**Comment by Mahsaap** [comment]
Stop missing to contributions that is a lost

**Comment by Syzuna** [comment]
https://github.com/TwitchLib/TwitchLib.EventSub.Webhooks/blob/main/TwitchLib.EventSub.Webhooks/Core/Models/HypeTrain/HypeTrainBase.cs

has TopContributions as its shared by all of the hypetrain subscription types I pulled the shared ones into a base class that the others inherit

**Comment by iProdigy** [comment]
> the shared ones into a base class that the others inherit

yep, i also do it the [same](https://github.com/twitch4j/twitch4j/blob/master/eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/HypeTrainBeginEvent.java) [way](https://github.com/twitch4j/twitch4j/blob/master/eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/HypeTrainEvent.java)

**Comment by Mahsaap** [comment]
Ya all good I missed the inheritance :)

**Comment by qqqq-collab** [comment]
Twiter

**Comment by qqqq-collab** [comment]
[]()

**Comment by qqqq-collab** [comment]
Ok

**Pull request merged**
